version: '3.3'
services:
  zby_crawlab_frontend:
    image: zby/crawlab_frontend
    container_name: crawlab_frontend
    ports:
      - "18080:8080"
    depends_on:
      - zby_crawlab_master
  zby_crawlab_master:
    image: zby/crawlab_backend
    container_name: zby_crawlab_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_NODE_NAME: "zby_crawlab_master"
      CRAWLAB_MONGO_HOST: "zby_mongo"
    ports:
      - "18000:8000"
      - "19666:9666"
      - "18888:8888"
    depends_on:
      - zby_mongo
  zby_crawlab_node01:
    image: zby/crawlab_backend
    container_name: zby_crawlab_node01
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_NODE_NAME: "zby_crawlab_node01"
      CRAWLAB_GRPC_ADDRESS: "zby_crawlab_master"
    depends_on:
      - zby_crawlab_master
  zby_crawlab_node02:
    image: zby/crawlab_backend
    container_name: zby_crawlab_node02
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_NODE_NAME: "zby_crawlab_node02"
      CRAWLAB_GRPC_ADDRESS: "zby_crawlab_master"
    depends_on:
      - zby_crawlab_master
      - zby_crawlab_node01
  zby_mongo:
    container_name: zby_mongo
    image: mongo:4.2
    restart: always
