FROM node:14 AS build

ADD . /app
WORKDIR /app/frontend
RUN rm /app/frontend/.npmrc

# install frontend
RUN npm i -g pnpm@7
RUN pnpm install
RUN pnpm run build
RUN /bin/sh /app/bin/update_docker_js_api_address.py

FROM nginx:1.27.2

# copy files
COPY --from=build /app/dist /app/dist
COPY --from=build /app/nginx/crawlab.conf /etc/nginx/conf.d/crawlab.conf