version: '3.3'
services:
  atta_crawlab_frontend:
    image: atta/crawlab_frontend
    container_name: atta_crawlab_frontend
    ports:
      - "18080:8080"
    depends_on:
      - atta_crawlab_master
  atta_crawlab_master:
    image: atta/crawlab_backend
    container_name: atta_crawlab_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_NODE_NAME: "atta_crawlab_master"
      CRAWLAB_MONGO_HOST: "atta_crawlab_mongo"
    ports:
      - "18000:8000"
      - "19666:9666"
      - "18888:8888"
    depends_on:
      - atta_crawlab_mongo
  atta_crawlab_node01:
    image: atta/crawlab_backend
    container_name: atta_crawlab_node01
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_NODE_NAME: "atta_crawlab_node01"
      CRAWLAB_GRPC_ADDRESS: "atta_crawlab_master"
    depends_on:
      - atta_crawlab_master
  atta_crawlab_node02:
    image: atta/crawlab_backend
    container_name: atta_crawlab_node02
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_NODE_NAME: "atta_crawlab_node02"
      CRAWLAB_GRPC_ADDRESS: "atta_crawlab_master"
    depends_on:
      - atta_crawlab_master
      - atta_crawlab_node01
  atta_crawlab_mongo:
    container_name: atta_crawlab_mongo
    image: mongo:4.2
    restart: always
