FROM golang:1.22

RUN go env -w GOPROXY=https://goproxy.io,https://goproxy.cn && \
    go env -w GO111MODULE="on"

# set as non-interactive
ENV DEBIAN_FRONTEND noninteractive


WORKDIR /app

COPY . .

RUN cp -r  backend/conf .
RUN cd backend && go mod tidy
RUN go build -o crawlab


# CMD ["/bin/bash","-c","/app/backend/crawlab","server"]