FROM node:14 AS build

ADD . /app
WORKDIR /app/frontend
RUN rm /app/frontend/.npmrc
ENV SASS_BINARY_SITE=https://npm.taobao.org/mirrors/node-sass/
RUN npm config set registry "http://registry.npm.taobao.org"

# install frontend
RUN npm i -g pnpm@7
RUN pnpm install
RUN pnpm run build
RUN python /app/bin/update_docker_js_api_address.py

FROM nginx:1.27.2

# copy files
COPY --from=build /app/frontend/dist /app/dist
COPY --from=build /app/nginx/crawlab.conf /etc/nginx/conf.d/crawlab.conf