version: '3.3'
services:
  master:
    image: zby/crawlab
    container_name: zby_crawlab_master
    environment:
      CRAWLAB_NODE_MASTER: "Y"
      CRAWLAB_NODE_NAME: "MASTER"
      CRAWLAB_MONGO_HOST: "zby_mongo"
    ports:
      - "9080:8080"
      - "9000:8000"
      - "9866:9666"
      - "9888:8888"
    depends_on:
      - mongo
  worker01:
    image: zby/crawlab
    container_name: zby_crawlab_node01
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_NODE_NAME: "Worker Node 01"
      CRAWLAB_GRPC_ADDRESS: "master"
    depends_on:
      - master
  worker02:
    image: zby/crawlab
    container_name: zby_crawlab_node02
    environment:
      CRAWLAB_NODE_MASTER: "N"
      CRAWLAB_NODE_NAME: "Worker Node 02"
      CRAWLAB_GRPC_ADDRESS: "master"
    depends_on:
      - master
      - worker01
  mongo:
    container_name: zby_mongo
    image: mongo:4.2
    restart: always
